services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-ssh-container
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin:/usr/local/bin
    networks:
      - jenkins-demo-network
    ports:
      # this is for ssh login
      - "2222:22"
      # why need nginx -> provide several benefits
      - "8086:8084"

# default driver: bridge
# web application with a front-end and a back-end database, placing both containers on the same bridge network, they can communicate with each other directly.
networks:
  jenkins-demo-network:
    driver: bridge

# without defined volume like this, Docker will create anonymous volume -> no name so hard to track, clean up and control
volumes:
  jenkins_home:
